### ISSUE TITLE
Regression in recent `git` gem releases

### ISSUE THREAD

**Issue by alexjfisher** [puppetlabs/pdksync#177]
There appears to be a regression in the recent versions of the `git` dependency.  If I don't pin to `1.14.0` I get the following failure in my pdksync pipeline.

Looks like the checkout command is invalid?? (If I run the git command manually and don't throw away the stderr, I get `error: pathspec 'pdksync_pdksync_tags/hl-latest-0-g76a98ec' did not match any file(s) known to git`)

I'm using `gitlab` instead of the more common `github`, but as this is a failure with a local git command, I _think_ this isn't relevant.
```
$ bundle exec rake pdksync
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
INFO - PdkSync: Commit branch_name=pdksync_{ref} commit_message=pdksync_{ref}
INFO - PdkSync: PR title = pdksync_{ref}
INFO - PdkSync: mymodule, 
INFO - PdkSync: delete module directory
INFO - PdkSync: cloned
WARN - PdkSync: (WARNING) Using pdk on PATH not '/opt/puppetlabs/pdk/bin/pdk'
INFO - PdkSync: pdk update
rake aborted!
Git::FailedError: git '--git-dir=/builds/example/puppet-platform/pdk/pdksync-config/modules_pdksync/mymodule/.git' '--work-tree=/builds/example/puppet-platform/pdk/pdksync-config/modules_pdksync/mymodule' '-c' 'core.quotePath=true' '-c' 'color.ui=false' 'checkout' 'pdksync_pdksync_tags/hl-latest-0-g76a98ec'  2>&1
status: pid 1843 exit 1
stderr: ""
/builds/example/puppet-platform/pdk/pdksync-config/vendor/bundle/ruby/2.7.0/gems/git-1.17.0/lib/git/lib.rb:1215:in `command'
/builds/example/puppet-platform/pdk/pdksync-config/vendor/bundle/ruby/2.7.0/gems/git-1.17.0/lib/git/lib.rb:834:in `checkout'
/builds/example/puppet-platform/pdk/pdksync-config/vendor/bundle/ruby/2.7.0/gems/git-1.17.0/lib/git/base.rb:359:in `checkout'
/builds/example/puppet-platform/pdk/pdksync-config/vendor/bundle/ruby/2.7.0/gems/git-1.17.0/lib/git/branch.rb:28:in `checkout'
/builds/example/puppet-platform/pdk/pdksync-config/vendor/bundle/ruby/2.7.0/bundler/gems/pdksync-25b4d3031c11/lib/pdksync/utils.rb:329:in `checkout_branch'
/builds/example/puppet-platform/pdk/pdksync-config/vendor/bundle/ruby/2.7.0/bundler/gems/pdksync-25b4d3031c11/lib/pdksync/utils.rb:195:in `create_commit'
```

**Comment by alexjfisher** [comment]
`ruby-git` `1.17.2` fixes the issue and `pdksync` is working again.  I don't think there's any particular need to set that as a minimum version here (since it's only a few versions released over a short period that are broken), so closing this.
